updating script

diff --git a/benchmarks/programs/stmbench7/benchmark b/benchmarks/programs/stmbench7/benchmark
--- a/benchmarks/programs/stmbench7/benchmark
+++ b/benchmarks/programs/stmbench7/benchmark
@@ -17,7 +17,12 @@ echo "------------------------Partial Abort----------------------------"
 for i in $(seq 1 $iters);
 do
     echo "Iteration $i"  
-    ./a.out -numOps 200 -p $threads  > currentTime.txt
+    res=$(./a.out -numOps 200 -p $threads  > currentTime.txt)
+    while [ $? -eq "139" ]; 
+    do
+        echo "Error!, trying again..."
+        res=$(./a.out -numOps 200 -p $threads > currentTime.txt)
+    done
     cat currentTime.txt
     echo "name = Partial Abort" >> times.txt
     cat currentTime.txt >> times.txt
@@ -28,7 +33,12 @@ echo "------------------------Full Abort----------------------------"
 for i in $(seq 1 $iters);
 do
     echo "Iteration $i"
-    ./a.out -numOps 200 -stm full -p $threads > currentTime.txt
+    res=$(./a.out -numOps 200 -p $threads -stm full > currentTime.txt)
+    while [ $? -eq "139" ]; 
+    do
+        echo "Error!, trying again..."
+        res=$(./a.out -numOps 200 -p $threads -stm full > currentTime.txt)
+    done
     cat currentTime.txt
     echo "name = Full Abort" >> times.txt
     cat currentTime.txt >> times.txt
