updating benchmark script

diff --git a/benchmarks/programs/stmbench7/benchmark b/benchmarks/programs/stmbench7/benchmark
--- a/benchmarks/programs/stmbench7/benchmark
+++ b/benchmarks/programs/stmbench7/benchmark
@@ -1,11 +1,18 @@
-pmlc mc.mlb
+#!/bin/bash
+
+#pmlc mc.mlb
 echo "" > times.txt
 trap "exit" INT
 echo "------------------------Partial Abort----------------------------"
 for i in {1..10}
 do
     echo "Iteration $i"
-    ./a.out -numAtomicPerComp 50 -numAssmLevels 4  > currentTime.txt
+    res=$(./a.out -numAtomicPerComp 50 -numAssmLevels 4  > currentTime.txt)
+    while [ $? -eq "139" ]; 
+    do
+        echo "Error!, trying again..."
+        res=$(./a.out -numAtomicPerComp 50 -numAssmLevels 4  > currentTime.txt)
+    done
     cat currentTime.txt
     cat currentTime.txt >> times.txt
 done
@@ -14,7 +21,12 @@ echo "------------------------Full Abort----------------------------"
 for i in {1..10}
 do
     echo "Iteration $i"
-    ./a.out -numAtomicPerComp 50 -numAssmLevels 4 -stm full > currentTime.txt
+    res=$(./a.out -numAtomicPerComp 50 -numAssmLevels 4 -stm full > currentTime.txt)
+    while [ $? -eq "139" ]; 
+    do
+        echo "Error!, trying again..."
+        res=$(./a.out -numAtomicPerComp 50 -numAssmLevels 4 -stm full > currentTime.txt)
+    done
     cat currentTime.txt
     cat currentTime.txt >> times.txt
 done
