updating

diff --git a/benchmarks/programs/linked-list-stm/benchmark-throughput b/benchmarks/programs/linked-list-stm/benchmark-throughput
--- a/benchmarks/programs/linked-list-stm/benchmark-throughput
+++ b/benchmarks/programs/linked-list-stm/benchmark-throughput
@@ -1,26 +1,23 @@
 echo "" > times.txt
 
-echo "------------------------Partial Abort----------------------------"
-for j in 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9
-do
-    for i in {1..5}
-    do
-        echo "Iteration $i"
-        ./a.out -split $j > currentTime.txt
-        cat currentTime.txt
-        cat currentTime.txt >> times.txt
-    done
-done 
+pmlc throughput.mlb
 
-echo "------------------------Full Abort----------------------------"
-for j in 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9
-do
-    for i in {1..5}
+trap "exit" INT
+
+echo "------------------------Partial Abort----------------------------"
+    for i in {1..10}
     do
         echo "Iteration $i"
-        ./a.out -split $j -stm full > currentTime.txt
+        ./a.out > currentTime.txt
         cat currentTime.txt
         cat currentTime.txt >> times.txt
     done
-done
+echo "------------------------Full Abort----------------------------"
+    for i in {1..10}
+    do
+        echo "Iteration $i"
+        ./a.out -stm full > currentTime.txt
+        cat currentTime.txt
+        cat currentTime.txt >> times.txt
+    done
 grep -o '[0-9]\+\.[0-9]\+\|[0-9]\+' times.txt > stripped.txt
