add bloaty & cachegrind data collection to mlton & pmlc runs

diff --git a/benchmarks/scripts/experiment-git_sh.in b/benchmarks/scripts/experiment-git_sh.in
--- a/benchmarks/scripts/experiment-git_sh.in
+++ b/benchmarks/scripts/experiment-git_sh.in
@@ -22,21 +22,21 @@ PRETTY_INPUT=""
 
 usage="See the README file for instructions"
 
-while getopts ":s:p:f:en:d:t:r:i:" options; 
+while getopts ":s:p:f:en:d:t:r:i:" options;
 do
     case $options in
-	s ) INPUT="$OPTARG";;
-	p ) PROCS="$PROCS $OPTARG";;
-	f ) BENCHMARK_PATH="$OPTARG";;
-	e ) SEQUENTIAL_BINARY="true";;
-	n ) EXPERIMENT_NAME="$OPTARG";;
-	d ) DESCRIPTION="$OPTARG";;
-	t ) NUM_TRIALS="$OPTARG";;
-	r ) MANTICORE_ROOT="$OPTARG";;
-	i ) PRETTY_INPUT="$OPTARG";;
-	\? ) echo $usage
+        s ) INPUT="$OPTARG";;
+        p ) PROCS="$PROCS $OPTARG";;
+        f ) BENCHMARK_PATH="$OPTARG";;
+        e ) SEQUENTIAL_BINARY="true";;
+        n ) EXPERIMENT_NAME="$OPTARG";;
+        d ) DESCRIPTION="$OPTARG";;
+        t ) NUM_TRIALS="$OPTARG";;
+        r ) MANTICORE_ROOT="$OPTARG";;
+        i ) PRETTY_INPUT="$OPTARG";;
+        \? ) echo $usage
             exit 1;;
-	* ) echo $usage
+        * ) echo $usage
             exit 1;;
     esac
 done
@@ -84,17 +84,17 @@ function metadata_list {
     n=0
     for x in $1
     do
-	n=$(( n + 1 ))
+        n=$(( n + 1 ))
     done
     cnt=0
     for x in $1
     do
-	if [ $cnt -lt $(( n - 1 )) ]; then
-	    echo -n -e " $x, " >> $LOG_FILE
-	else 
-	    echo -n -e " $x " >> $LOG_FILE
-	fi
-	cnt=$(( cnt + 1 ))
+        if [ $cnt -lt $(( n - 1 )) ]; then
+            echo -n -e " $x, " >> $LOG_FILE
+        else
+            echo -n -e " $x " >> $LOG_FILE
+        fi
+        cnt=$(( cnt + 1 ))
     done
     echo -e "]," >> $LOG_FILE
 }
@@ -104,7 +104,9 @@ EXPERIMENT_RESULTS_DIR="$RESULTS_DIR/$EXPERIMENT_NAME"
 if [ ! -e $EXPERIMENT_RESULTS_DIR ]; then
     mkdir $EXPERIMENT_RESULTS_DIR
 fi
-LOG_FILE="$EXPERIMENT_RESULTS_DIR/$EXPERIMENT_NAME-$DATETIME.json"
+LOG_FILE="$EXPERIMENT_RESULTS_DIR/$EXPERIMENT_NAME-$DESCRIPTION-$DATETIME.json"
+GRIND_FILE="$EXPERIMENT_RESULTS_DIR/$EXPERIMENT_NAME-$DESCRIPTION-$DATETIME.cg"
+SIZE_FILE="$EXPERIMENT_RESULTS_DIR/$EXPERIMENT_NAME-$DESCRIPTION-size-$DATETIME.csv"
 DATETIME_SML=${DATETIME//-/_}
 DATETIME_MD=$( date +"%F %H:%M:%S" )
 
@@ -137,7 +139,7 @@ pushd $MANTICORE_ROOT > /dev/null
     # COMPILER_SVN_URL=${COMPILER_SVN_URL:5}
     # COMPILER_SVN_STATUS=$( svn st -q | wc -l )
     # if [ $COMPILER_SVN_STATUS != "0" ]; then
-	# echo "WARNING: not all changes have been committed to the compiler"
+        # echo "WARNING: not all changes have been committed to the compiler"
     # fi
 popd > /dev/null
 
@@ -189,76 +191,82 @@ fi
 if [ $SEQUENTIAL_BINARY == "true" ]; then
     cnt=0
     SEQUENTIAL_EXE=$BENCHMARK_PATH
+    # gather size info with bloaty
+    echo "running bloaty..."
+    bloaty --csv -d compileunits $SEQUENTIAL_EXE > $SIZE_FILE
+    # run the executable with cachegrind once
+    echo "running cachegrind..."
+    valgrind --tool=cachegrind --branch-sim=yes --cachegrind-out-file="$GRIND_FILE" $SEQUENTIAL_EXE $ARGS
     echo "\"runs\" : [" >> $LOG_FILE
     for ((i=1;i<=NUM_TRIALS;i+=1)); do
-	echo "$SEQUENTIAL_EXE $ARGS"
-	RES=$( $SEQUENTIAL_EXE $ARGS 2> stats.json )
-	if [ $? == "0" ]; then
-	    echo -n -e "\t\t{ \"n_procs\" : 0,\t\t\"time_sec\" : " >> $LOG_FILE
-	    echo -n -e "$RES" >> $LOG_FILE
-	    echo -n -e ",\t\t" >> $LOG_FILE
-	    if [ $GEN_GC_STATS == "false" ]; then
-		echo -n -e "\"gc\" : []" >> $LOG_FILE
-	    else
-		echo -n -e "\"gc\" : \"" >> $LOG_FILE
-		cat stats.json >> $LOG_FILE
-		echo -n -e "\"" >> $LOG_FILE
-		rm -rf stats.json
-	    fi
-	else
-	    echo "Benchmark failed unexpectedly with nonzero return code"
-	    exit 1
-	fi
-	echo -n -e "}" >> $LOG_FILE
-	if [ $cnt -lt $(( $NUM_TRIALS - 1 )) ]; then
-	    echo -e "," >> $LOG_FILE
-	fi
-	cnt=$(( $cnt + 1 ))
+        echo "$SEQUENTIAL_EXE $ARGS"
+        RES=$( $SEQUENTIAL_EXE $ARGS 2> stats.json )
+        if [ $? == "0" ]; then
+            echo -n -e "\t\t{ \"n_procs\" : 0,\t\t\"time_sec\" : " >> $LOG_FILE
+            echo -n -e "$RES" >> $LOG_FILE
+            echo -n -e ",\t\t" >> $LOG_FILE
+            if [ $GEN_GC_STATS == "false" ]; then
+                echo -n -e "\"gc\" : []" >> $LOG_FILE
+            else
+                echo -n -e "\"gc\" : \"" >> $LOG_FILE
+                cat stats.json >> $LOG_FILE
+                echo -n -e "\"" >> $LOG_FILE
+                rm -rf stats.json
+            fi
+        else
+            echo "Benchmark failed unexpectedly with nonzero return code"
+            exit 1
+        fi
+        echo -n -e "}" >> $LOG_FILE
+        if [ $cnt -lt $(( $NUM_TRIALS - 1 )) ]; then
+            echo -e "," >> $LOG_FILE
+        fi
+        cnt=$(( $cnt + 1 ))
     done
     echo -e "\t\t]" >> $LOG_FILE
 else
     n=0
     for ((i=1;i<=NUM_TRIALS;i+=1)); do
-	for p in $PROCS; do
-	    n=$(( $n + 1 ))
-	done
+        for p in $PROCS; do
+            n=$(( $n + 1 ))
+        done
     done
 
     PARALLEL_EXE=$BENCHMARK_PATH
     echo "\"runs\" : [" >> $LOG_FILE
     cnt=0
     for ((i=1;i<=NUM_TRIALS;i+=1)); do
-	for p in $PROCS; do
-	    echo "$PARALLEL_EXE -p $p $ARGS"
-	    RES=$( $PARALLEL_EXE -p $p $ARGS 2> stats.json )
-	    retcode=$?
-	    nretries=0
-	    while [ $retcode != "0" ]; do
-		let nretries=nretries+1
-		echo "Benchmark failed unexpectedly with nonzero return code -- retrying."
-		RES=$( $PARALLEL_EXE -p $p $ARGS 2> stats.json )
-		retcode=$?
-		if [ $nretries -gt 100 ]; then
-		    echo "Exceeded maximum number of failed executions of the benchmark"
-		    exit 1
-		fi
-	    done
-	    echo -n -e "\t\t{ \"n_procs\" : $p,\t\t\"time_sec\" : " >> $LOG_FILE
-	    echo -n -e "$RES" >> $LOG_FILE
-	    echo -n -e ",\t\t" >> $LOG_FILE
-	    if [ $GEN_GC_STATS == "false" ]; then
-		echo -n -e "\"gc\" : []" >> $LOG_FILE
-	    else
-		echo -n -e "\"gc\" :" >> $LOG_FILE
-		cat stats.json >> $LOG_FILE
-		rm -rf stats.json
-	    fi 
-	    echo -n "}" >> $LOG_FILE
-	    if [ $cnt -lt $(( $n - 1 )) ]; then
-		echo -e "," >> $LOG_FILE
-	    fi
-	    cnt=$(( cnt + 1 ))
-	done
+        for p in $PROCS; do
+            echo "$PARALLEL_EXE -p $p $ARGS"
+            RES=$( $PARALLEL_EXE -p $p $ARGS 2> stats.json )
+            retcode=$?
+            nretries=0
+            while [ $retcode != "0" ]; do
+                let nretries=nretries+1
+                echo "Benchmark failed unexpectedly with nonzero return code -- retrying."
+                RES=$( $PARALLEL_EXE -p $p $ARGS 2> stats.json )
+                retcode=$?
+                if [ $nretries -gt 100 ]; then
+                    echo "Exceeded maximum number of failed executions of the benchmark"
+                    exit 1
+                fi
+            done
+            echo -n -e "\t\t{ \"n_procs\" : $p,\t\t\"time_sec\" : " >> $LOG_FILE
+            echo -n -e "$RES" >> $LOG_FILE
+            echo -n -e ",\t\t" >> $LOG_FILE
+            if [ $GEN_GC_STATS == "false" ]; then
+                echo -n -e "\"gc\" : []" >> $LOG_FILE
+            else
+                echo -n -e "\"gc\" :" >> $LOG_FILE
+                cat stats.json >> $LOG_FILE
+                rm -rf stats.json
+            fi
+            echo -n "}" >> $LOG_FILE
+            if [ $cnt -lt $(( $n - 1 )) ]; then
+                echo -e "," >> $LOG_FILE
+            fi
+            cnt=$(( cnt + 1 ))
+        done
     done
     echo -e "\t\t]" >> $LOG_FILE
 fi
diff --git a/benchmarks/scripts/experiment_mlton_sh.in b/benchmarks/scripts/experiment_mlton_sh.in
--- a/benchmarks/scripts/experiment_mlton_sh.in
+++ b/benchmarks/scripts/experiment_mlton_sh.in
@@ -17,17 +17,17 @@ NUM_TRIALS="1"
 
 usage="See the README file for instructions"
 
-while getopts ":s:f:n:d:t:" options; 
+while getopts ":s:f:n:d:t:" options;
 do
     case $options in
-	s ) INPUT="$OPTARG";;
-	f ) BENCHMARK_EXE="$OPTARG";;
-	n ) EXPERIMENT_NAME="$OPTARG";;
-	d ) DESCRIPTION="$OPTARG";;
-	t ) NUM_TRIALS="$OPTARG";;
-	\? ) echo $usage
+        s ) INPUT="$OPTARG";;
+        f ) BENCHMARK_EXE="$OPTARG";;
+        n ) EXPERIMENT_NAME="$OPTARG";;
+        d ) DESCRIPTION="$OPTARG";;
+        t ) NUM_TRIALS="$OPTARG";;
+        \? ) echo $usage
             exit 1;;
-	* ) echo $usage
+        * ) echo $usage
             exit 1;;
     esac
 done
@@ -54,17 +54,17 @@ function metadata_list {
     n=0
     for x in $1
     do
-	n=$(( n + 1 ))
+        n=$(( n + 1 ))
     done
     cnt=0
     for x in $1
     do
-	if [ $cnt -lt $(( n - 1 )) ]; then
-	    echo -n -e " $x, " >> $LOG_FILE
-	else 
-	    echo -n -e " $x " >> $LOG_FILE
-	fi
-	cnt=$(( cnt + 1 ))
+        if [ $cnt -lt $(( n - 1 )) ]; then
+            echo -n -e " $x, " >> $LOG_FILE
+        else
+            echo -n -e " $x " >> $LOG_FILE
+        fi
+        cnt=$(( cnt + 1 ))
     done
     echo -e "]," >> $LOG_FILE
 }
@@ -74,7 +74,9 @@ EXPERIMENT_RESULTS_DIR="$RESULTS_DIR/$EXPERIMENT_NAME"
 if [ ! -e $EXPERIMENT_RESULTS_DIR ]; then
     mkdir $EXPERIMENT_RESULTS_DIR
 fi
-LOG_FILE="$EXPERIMENT_RESULTS_DIR/$EXPERIMENT_NAME-$DATETIME.json"
+LOG_FILE="$EXPERIMENT_RESULTS_DIR/$EXPERIMENT_NAME-$DESCRIPTION-$DATETIME.json"
+GRIND_FILE="$EXPERIMENT_RESULTS_DIR/$EXPERIMENT_NAME-$DESCRIPTION-$DATETIME.cg"
+SIZE_FILE="$EXPERIMENT_RESULTS_DIR/$EXPERIMENT_NAME-$DESCRIPTION-size-$DATETIME.csv"
 DATETIME_SML=${DATETIME//-/_}
 DATETIME_MD=$( date +"%F %H:%M:%S" )
 
@@ -125,6 +127,13 @@ metadata "nTrials" "$NUM_TRIALS"
 
 # Build and run the benchmarks
 
+# gather size info with bloaty
+echo "running bloaty..."
+bloaty --csv "./$BENCHMARK_EXE" > $SIZE_FILE
+# run the executable with cachegrind once
+echo "running cachegrind..."
+valgrind --tool=cachegrind --branch-sim=yes --cachegrind-out-file="$GRIND_FILE" "./$BENCHMARK_EXE" $INPUT
+
 echo "Logging performance results to $LOG_FILE"
 
 cnt=0
@@ -133,13 +142,13 @@ for ((i=1;i<=NUM_TRIALS;i+=1)); do
     echo "./$BENCHMARK_EXE $INPUT"
     RES=$( ./$BENCHMARK_EXE $INPUT )
     if [ $? == "0" ]; then
-	echo -n -e "\t\t{ \"n_procs\" : 0,\t\t\"time_sec\" : " >> $LOG_FILE
-	echo -n -e "$RES" >> $LOG_FILE
-	echo -n -e ",\t\t" >> $LOG_FILE
-	echo -n -e "\"gc\" : []" >> $LOG_FILE
+        echo -n -e "\t\t{ \"n_procs\" : 0,\t\t\"time_sec\" : " >> $LOG_FILE
+        echo -n -e "$RES" >> $LOG_FILE
+        echo -n -e ",\t\t" >> $LOG_FILE
+        echo -n -e "\"gc\" : []" >> $LOG_FILE
     else
-	echo "Benchmark failed unexpectedly with nonzero return code"
-	exit 1
+        echo "Benchmark failed unexpectedly with nonzero return code"
+        exit 1
     fi
     echo -n -e "}" >> $LOG_FILE
     if [ $cnt -lt $(( $NUM_TRIALS - 1 )) ]; then
